### PR TITLE
feat: add op-besu

### PR DESCRIPTION
**Pull request by barnabasbusa**

### CODE REVIEW

**Comment by barnabasbusa** [comment]
Currently failing with:
```
2024-08-09 11:26:07.291+00:00 | main | ERROR | Besu | Failed to start Besu
  java.io.FileNotFoundException: /data/besu/execution-data/VERSION_METADATA.json (No such file or directory)
        at java.base/java.io.FileOutputStream.open0(Native Method)
        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:289)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:230)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:179)
        at com.fasterxml.jackson.core.TokenStreamFactory._fileOutputStream(TokenStreamFactory.java:334)
        at com.fasterxml.jackson.core.JsonFactory.createGenerator(JsonFactory.java:1547)
        at com.fasterxml.jackson.databind.ObjectMapper.createGenerator(ObjectMapper.java:1257)
        at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:3980)
        at org.hyperledger.besu.ethereum.core.VersionMetadata.writeToDirectory(VersionMetadata.java:71)
        at org.hyperledger.besu.ethereum.core.VersionMetadata.versionCompatibilityChecks(VersionMetadata.java:119)
        at org.hyperledger.besu.cli.BesuCommand.run(BesuCommand.java:1173)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at org.hyperledger.besu.cli.BesuCommand.lambda$createExecuteTask$1(BesuCommand.java:1100)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at org.hyperledger.besu.cli.BesuCommand.lambda$createPluginRegistrationTask$2(BesuCommand.java:1110)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at org.hyperledger.besu.cli.util.
ConfigDefaultValueProviderStrategy.execute(ConfigDefaultValueProviderStrategy.java:58)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at org.hyperledger.besu.cli.BesuCommand.executeCommandLine(BesuCommand.java:1137)
        at org.hyperledger.besu.cli.BesuCommand.parse(BesuCommand.java:1079)
        at org.hyperledger.besu.Besu.main(Besu.java:41)
```

cc: @GrapeBaBa

**Comment by thinkAfCod** [comment]
The startup parameters should also include --version-compatibility-protection=false to avoid this error.

**Comment by barnabasbusa** [comment]
@thinkAfCod how can pass the rollup's sequencer's IP:port to op-besu? `--rollup.sequencerhttp=` doesn't seem to be a valid flag.

**Comment by barnabasbusa** [comment]
even with `--version-compatibility-protection=false` added, I'm still getting the above listed error about the metadata json file missing.

**Comment by thinkAfCod** [comment]
The default user for Besu's Docker container is 'besu,' not 'root,' which imposes significant permission restrictions. You can try specifying the data-path to the /opt/besu directory.

**Comment by GrapeBaBa** [comment]
> The default user for Besu's Docker container is 'besu,' not 'root,' which imposes significant permission restrictions. You can try specifying the data-path to the /opt/besu directory.

@barnabasbusa does it make sense? This is inherited from the origin besu.

**Comment by barnabasbusa** [comment]
@thinkAfCod seems like besu now started up, but seem to be unable to build blocks with op-node:
```
t=2024-08-26T11:50:12+0000 lvl=error msg="Sequencer temporarily could not seal block" payloadID=0x1dbaadc0b59c8495 timestamp=1724672521 err="failed to seal execution payload (ID: 0x1dbaadc0b59c8495): unrecognized rpc error: Method not enabled"
```
l1.rpckind is set to `standard` on op-node.

**Review by parithosh — APPROVED** [review]

**Pull request merged**
