### PR TITLE
feat: add hildr

### PR DESCRIPTION
**Pull request by barnabasbusa**

### CODE REVIEW

**Comment by barnabasbusa** [comment]
cc: @GrapeBaBa

**Comment by thinkAfCod** [comment]
The sequencer functionality of hildr is not yet completed.So users only need to start op-geth when using hildr.

**Comment by barnabasbusa** [comment]
what does `--enable-sequencer` flag do then?

**Comment by thinkAfCod** [comment]
> So hildr is incapable of block production without op-node?

yes, it is now.

**Comment by thinkAfCod** [comment]
> what does `--enable-sequencer` flag do then?

This is predefined. Although it currently has no effect, it will be used to start the sequencer function once Hildr's sequencer feature is implemented.

**Comment by GrapeBaBa** [comment]
@barnabasbusa I am on vacation, @thinkAfCod would help to fix any blocking issue for this PR.

**Comment by GrapeBaBa** [comment]
@barnabasbusa please use latest version to check again.

**Comment by barnabasbusa** [comment]
Looks a lot better, we seem to have hildr working with `op-geth`, `op-reth`, `op-erigon`

Screenshot 2024-07-15 at 14 51 41

**Review by pk910 — APPROVED** [review]

**Pull request merged**
