### PR TITLE
chore: set proof window

### PR DESCRIPTION
**Pull request by onbjerg**
Currently `optimism_outputAtBlock` fails on op-reth because the proof window size defaults to 0. This sets it to 302400, which is roughly 1 week on a 2 second block time.

### CODE REVIEW

**Review by parithosh — APPROVED** [review]

**Comment by parithosh** [comment]
CI fails with this btw `  error: invalid value '302400' for '--rpc.eth-proof-window <RPC_ETH_PROOF_WINDOW>': 302400 is not in 0..=216000` @onbjerg

**Comment by onbjerg** [comment]
yeah sorry, this requires a release from our end. will ping here when it is

**Comment by onbjerg** [comment]
@parithosh this should work now on the latest image:)

**Comment by onbjerg** [comment]
Failure seems unrelated?

**Comment by parithosh** [comment]
@onbjerg Yup agreed, error is unrelated :)
Merging the PR in now

**Pull request merged**
